=== ShriGanesh-Purohit/CU-MCA-172-WEB-STACK-LAB-EXERSISE-5/stocks.dtd
<!ELEMENT stocks (stocksymbole+)>
<!ELEMENT stocksymbole (companyname, sector, currentprice, pbratio, peratio, roe, marketcapitalisation, dateadded)>
<!ELEMENT companyname (#PCDATA)>
<!ELEMENT sector (#PCDATA)>
<!ELEMENT currentprice (#PCDATA)>
<!ELEMENT pbratio (#PCDATA)>
<!ELEMENT peratio (#PCDATA)>
<!ELEMENT roe (#PCDATA)>
<!ELEMENT marketcapitalisation (#PCDATA)>
<!ELEMENT dateadded (#PCDATA)>

=== ShriGanesh-Purohit/CU-MCA-172-WEB-STACK-LAB-EXERSISE-5/stocks.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="stocks.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<!DOCTYPE stocks SYSTEM "stocks.dtd">
<?xml-stylesheet type="text/xsl" href="stocks.xslt"?>

<stocks>
    <stocksymbole>
        <companyname>Reliance Industries</companyname>
        <sector>Conglomerate</sector>
        <currentprice>2948.60</currentprice>
        <pbratio>2.51</pbratio>
        <peratio>29.02</peratio>
        <roe>9.25</roe>
        <marketcapitalisation>1994967.85</marketcapitalisation>
        <dateadded>2024-06-01</dateadded>
    </stocksymbole>
    <stocksymbole>
        <companyname>Tata Consultancy Services</companyname>
        <sector>Information Technology</sector>
        <currentprice>4228.75</currentprice>
        <pbratio>16.91</pbratio>
        <peratio>32.15</peratio>
        <roe>51.51</roe>
        <marketcapitalisation>1529998.76</marketcapitalisation>
        <dateadded>2024-06-01</dateadded>
    </stocksymbole>
    <stocksymbole>
        <companyname>HDFC Bank</companyname>
        <sector>Banking</sector>
        <currentprice>1650.20</currentprice>
        <pbratio>2.75</pbratio>
        <peratio>18.44</peratio>
        <roe>17.14</roe>
        <marketcapitalisation>1257038.75</marketcapitalisation>
        <dateadded>2024-06-01</dateadded>
    </stocksymbole>
    <stocksymbole>
        <companyname>Bharti Airtel</companyname>
        <sector>Telecommunications</sector>
        <currentprice>1464.10</currentprice>
        <pbratio>10.09</pbratio>
        <peratio>73.30</peratio>
        <roe>14.93</roe>
        <marketcapitalisation>875500.65</marketcapitalisation>
        <dateadded>2024-06-01</dateadded>
    </stocksymbole>
    <stocksymbole>
        <companyname>ICICI Bank</companyname>
        <sector>Banking</sector>
        <currentprice>1171.60</currentprice>
        <pbratio>3.21</pbratio>
        <peratio>18.20</peratio>
        <roe>18.80</roe>
        <marketcapitalisation>824608.00</marketcapitalisation>
        <dateadded>2024-06-01</dateadded>
    </stocksymbole>
    <stocksymbole>
        <companyname>State Bank of India</companyname>
        <sector>Banking</sector>
        <currentprice>824.30</currentprice>
        <pbratio>1.77</pbratio>
        <peratio>10.09</peratio>
        <roe>17.34</roe>
        <marketcapitalisation>735655.76</marketcapitalisation>
        <dateadded>2024-06-01</dateadded>
    </stocksymbole>
    <stocksymbole>
        <companyname>Infosys</companyname>
        <sector>Information Technology</sector>
        <currentprice>1770.75</currentprice>
        <pbratio>8.85</pbratio>
        <peratio>27.58</peratio>
        <roe>31.83</roe>
        <marketcapitalisation>735220.44</marketcapitalisation>
        <dateadded>2024-06-01</dateadded>
    </stocksymbole>
    <stocksymbole>
        <companyname>Hindustan Unilever</companyname>
        <sector>FMCG</sector>
        <currentprice>2747.20</currentprice>
        <pbratio>12.60</pbratio>
        <peratio>62.46</peratio>
        <roe>20.24</roe>
        <marketcapitalisation>645479.71</marketcapitalisation>
        <dateadded>2024-06-01</dateadded>
    </stocksymbole>
    <stocksymbole>
        <companyname>ITC</companyname>
        <sector>FMCG</sector>
        <currentprice>495.90</currentprice>
        <pbratio>8.31</pbratio>
        <peratio>30.31</peratio>
        <roe>28.43</roe>
        <marketcapitalisation>620016.91</marketcapitalisation>
        <dateadded>2024-06-01</dateadded>
    </stocksymbole>
    <stocksymbole>
        <companyname>Larsen and Toubro</companyname>
        <sector>Engineering</sector>
        <currentprice>3592.05</currentprice>
        <pbratio>5.72</pbratio>
        <peratio>37.16</peratio>
        <roe>14.68</roe>
        <marketcapitalisation>493852.31</marketcapitalisation>
        <dateadded>2024-06-01</dateadded>
    </stocksymbole>
    <stocksymbole>
        <companyname>HCL Technologies</companyname>
        <sector>Information Technology</sector>
        <currentprice>1589.95</currentprice>
        <pbratio>6.32</pbratio>
        <peratio>26.27</peratio>
        <roe>23.30</roe>
        <marketcapitalisation>431495.18</marketcapitalisation>
        <dateadded>2024-06-01</dateadded>
    </stocksymbole>
    <stocksymbole>
        <companyname>Oil and Natural Gas Corporation</companyname>
        <sector>Energy</sector>
        <currentprice>332.55</currentprice>
        <pbratio>1.24</pbratio>
        <peratio>9.18</peratio>
        <roe>16.28</roe>
        <marketcapitalisation>418357.19</marketcapitalisation>
        <dateadded>2024-06-01</dateadded>
    </stocksymbole>
    <stocksymbole>
        <companyname>Sun Pharmaceuticals</companyname>
        <sector>Pharmaceuticals</sector>
        <currentprice>1735.30</currentprice>
        <pbratio>6.54</pbratio>
        <peratio>39.49</peratio>
        <roe>16.69</roe>
        <marketcapitalisation>416356.60</marketcapitalisation>
        <dateadded>2024-06-01</dateadded>
    </stocksymbole>
    <stocksymbole>
        <companyname>Bajaj Finance</companyname>
        <sector>NBFC</sector>
        <currentprice>6618.20</currentprice>
        <pbratio>5.36</pbratio>
        <peratio>27.45</peratio>
        <roe>22.12</roe>
        <marketcapitalisation>409664.14</marketcapitalisation>
        <dateadded>2024-06-01</dateadded>
    </stocksymbole>
    <stocksymbole>
        <companyname>NTPC</companyname>
        <sector>Energy</sector>
        <currentprice>410.65</currentprice>
        <pbratio>2.48</pbratio>
        <peratio>18.60</peratio>
        <roe>13.62</roe>
        <marketcapitalisation>398193.59</marketcapitalisation>
        <dateadded>2024-06-01</dateadded>
    </stocksymbole>
</stocks>
